### ISSUE TITLE
Create List activity

### ISSUE THREAD

**Issue by yev-kanivets** [evgenii-kanivets/mobile_techs#5]
1. Add following UI: EditText with search button on top. RecyclerView with short weather items.
2. Use WeatherRepoProvider to get WeatherRepo.
3. Fetch data for needed query using WeatherRepo.
4. Open Details screen after click on list item.
5. Pass WeatherEntry as Parcelable to Details screen.
6. Display for every item: date and time, weather summary (snow, cloudy, etc.), min/max temp.

**Comment by ObidosDev** [comment]
Added recyclerView and adapter for it, but they must be customized.
